ExcludeDirectories:
  - "EffekseeLib"
  - "vcpkg_installed"
  - "ImGui" 
  - "packages" 
MaxDegreeOfParallelism: 4
CodeGenerationRules:
  -  ClassMetadataType: "MT_COMPONENT"
     MemberMetadataType: "MT_PROPERTY"
     OutputTemplate: "Tools/ClangReflection/GenerateComponentHeader.sbn"