<Project>
  <PropertyGroup>
    <!-- 環境変数 LLVM_INSTALL_DIR を参照 -->
    <ClangTidyToolPath>$(LLVM_INSTALL_DIR)\bin</ClangTidyToolPath>
    <ClangTidyToolExe>$(SolutionDir)scripts\dist\clang-tidy-wrapper.exe</ClangTidyToolExe>
	
	<LLVMToolsVersion>21.1.0</LLVMToolsVersion>
	<LLVMInstallDir>$(LLVM_INSTALL_DIR)</LLVMInstallDir>

  </PropertyGroup>
</Project>