var optional_2optional_8hpp =
[
    [ "boost::optional_detail::optional_value_type< T >", "structboost_1_1optional__detail_1_1optional__value__type.html", null ],
    [ "boost::optional_detail::optional_value_type< ::boost::optional< U > >", "structboost_1_1optional__detail_1_1optional__value__type_3_01_1_1boost_1_1optional_3_01U_01_4_01_4.html", "structboost_1_1optional__detail_1_1optional__value__type_3_01_1_1boost_1_1optional_3_01U_01_4_01_4" ],
    [ "boost::optional_detail::result_of< F, Ref, Rslt >", "structboost_1_1optional__detail_1_1result__of.html", "structboost_1_1optional__detail_1_1result__of" ],
    [ "boost::optional_detail::result_value_type< F, Ref, Rslt >", "structboost_1_1optional__detail_1_1result__value__type.html", "structboost_1_1optional__detail_1_1result__value__type" ],
    [ "boost::optional_ns::in_place_init_t", "structboost_1_1optional__ns_1_1in__place__init__t.html", "structboost_1_1optional__ns_1_1in__place__init__t" ],
    [ "boost::optional_ns::in_place_init_t::init_tag", "structboost_1_1optional__ns_1_1in__place__init__t_1_1init__tag.html", null ],
    [ "boost::optional_ns::in_place_init_if_t", "structboost_1_1optional__ns_1_1in__place__init__if__t.html", "structboost_1_1optional__ns_1_1in__place__init__if__t" ],
    [ "boost::optional_ns::in_place_init_if_t::init_tag", "structboost_1_1optional__ns_1_1in__place__init__if__t_1_1init__tag.html", null ],
    [ "boost::optional_detail::init_value_tag", "structboost_1_1optional__detail_1_1init__value__tag.html", null ],
    [ "boost::optional_detail::optional_tag", "structboost_1_1optional__detail_1_1optional__tag.html", null ],
    [ "boost::optional_detail::optional_base< T >", "classboost_1_1optional__detail_1_1optional__base.html", "classboost_1_1optional__detail_1_1optional__base" ],
    [ "boost::optional_detail::is_optional_or_tag< U >", "structboost_1_1optional__detail_1_1is__optional__or__tag.html", "structboost_1_1optional__detail_1_1is__optional__or__tag" ],
    [ "boost::optional_detail::has_dedicated_constructor< T, U >", "structboost_1_1optional__detail_1_1has__dedicated__constructor.html", "structboost_1_1optional__detail_1_1has__dedicated__constructor" ],
    [ "boost::optional_detail::is_in_place_factory< U >", "structboost_1_1optional__detail_1_1is__in__place__factory.html", "structboost_1_1optional__detail_1_1is__in__place__factory" ],
    [ "boost::optional_detail::is_factory_or_constructible_to_T< T, U >", "structboost_1_1optional__detail_1_1is__factory__or__constructible__to__T.html", "structboost_1_1optional__detail_1_1is__factory__or__constructible__to__T" ],
    [ "boost::optional_detail::is_optional_constructible< T, U >", "structboost_1_1optional__detail_1_1is__optional__constructible.html", "structboost_1_1optional__detail_1_1is__optional__constructible" ],
    [ "boost::optional_detail::is_opt_assignable< T, U >", "structboost_1_1optional__detail_1_1is__opt__assignable.html", "structboost_1_1optional__detail_1_1is__opt__assignable" ],
    [ "boost::optional_detail::is_factory_or_opt_assignable_to_T< T, U >", "structboost_1_1optional__detail_1_1is__factory__or__opt__assignable__to__T.html", "structboost_1_1optional__detail_1_1is__factory__or__opt__assignable__to__T" ],
    [ "boost::optional_detail::is_optional_val_init_candidate< T, U, bool >", "structboost_1_1optional__detail_1_1is__optional__val__init__candidate.html", "structboost_1_1optional__detail_1_1is__optional__val__init__candidate" ],
    [ "boost::optional_detail::is_optional_val_init_candidate< T, U, false >", "structboost_1_1optional__detail_1_1is__optional__val__init__candidate_3_01T_00_01U_00_01false_01_4.html", "structboost_1_1optional__detail_1_1is__optional__val__init__candidate_3_01T_00_01U_00_01false_01_4" ],
    [ "boost::optional_detail::is_optional_val_assign_candidate< T, U, bool >", "structboost_1_1optional__detail_1_1is__optional__val__assign__candidate.html", "structboost_1_1optional__detail_1_1is__optional__val__assign__candidate" ],
    [ "boost::optional_detail::is_optional_val_assign_candidate< T, U, false >", "structboost_1_1optional__detail_1_1is__optional__val__assign__candidate_3_01T_00_01U_00_01false_01_4.html", "structboost_1_1optional__detail_1_1is__optional__val__assign__candidate_3_01T_00_01U_00_01false_01_4" ],
    [ "boost::optional_config::optional_uses_direct_storage_for< T >", "structboost_1_1optional__config_1_1optional__uses__direct__storage__for.html", "structboost_1_1optional__config_1_1optional__uses__direct__storage__for" ],
    [ "boost::optional< T >", "classboost_1_1optional.html", "classboost_1_1optional" ],
    [ "boost::optional< T && >", "classboost_1_1optional_3_01T_01_6_6_01_4.html", null ],
    [ "BOOST_OPTIONAL_BASE_TYPE", "optional_2optional_8hpp.html#a83af2a1f7597b9ce03a4ce1e6e120094", null ],
    [ "declval", "optional_2optional_8hpp.html#a0dcaf7fbb9f1fb64cd0d7a5ad215b530", null ],
    [ "get", "optional_2optional_8hpp.html#a3aa79321edf21167673e50eaabc42325", null ],
    [ "get", "optional_2optional_8hpp.html#ab26586e71de32238fb55a14efaac626f", null ],
    [ "get", "optional_2optional_8hpp.html#abc3d16ad987b43d95ba679ca15bd2dcb", null ],
    [ "get", "optional_2optional_8hpp.html#a838e5c557c091369c1390fdd72cd004d", null ],
    [ "get_optional_value_or", "optional_2optional_8hpp.html#a74e705c659bf3b321415c7d47229eb4c", null ],
    [ "get_optional_value_or", "optional_2optional_8hpp.html#aedfc4be38479426a3cbd350de996a2ac", null ],
    [ "get_pointer", "optional_2optional_8hpp.html#a30ea7e7071b80153cc799e58544fd5ec", null ],
    [ "get_pointer", "optional_2optional_8hpp.html#a02fde0c96f433893d9a06e20b0941e79", null ],
    [ "in_place_init", "optional_2optional_8hpp.html#a56b8bc62e86f7ebcedb3020c985fdfd3", null ],
    [ "in_place_init_if", "optional_2optional_8hpp.html#abe8afc1990a65b5c13fc6ee179fe9f61", null ],
    [ "make_optional", "optional_2optional_8hpp.html#aea0103d0618382a2ff6b69c540569f14", null ],
    [ "make_optional", "optional_2optional_8hpp.html#a52c1c67ac11c1fd2c4ac6b1d10e7d2a8", null ],
    [ "operator<<", "optional_2optional_8hpp.html#afffda37c0dfff2fa033e522f59845334", null ]
];