name: Code Analysis with clang-tidy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  clang-tidy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild (for dev environment)
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: '6.x'

      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install compdb (for generate compilation database with header files)
        run: python -m pip install --upgrade pip && python -m pip install compdb
    # キャッシュを復元
      - name: Restore NuGet packages
        run: nuget restore Game.sln

      - name: Restore FBX SDK cache
        uses: actions/cache@v4
        with:
          path: C:\fbxsdk
          key: fbx-sdk-202037-${{ hashFiles('**/FBXVersion.txt') }}
          restore-keys: |
            fbx-sdk-202037-
          fail-on-cache-miss: false
   # llvmをインストール
      - name: Install LLVM(clang-tidy)
        shell: powershell
        run: |
          choco install llvm -y --no-progress
          clang-tidy --version

  # clang-tidyで解析
      - name: Run clang-tidy analysis
        run: msbuild /t:ClangTidy Game.sln
