name: Release Build and Publish

on:
 push:
  tags:
   - 'v*'

permissions:
 contents: write

 # 実行中にまたプッシュされた場合、古い実行をキャンセルする
concurrency:
  group: release-${{ github.ref }}

jobs:
 build-and-release:
  # windows環境で動かす
  runs-on: windows-latest
  env:
   FBX: 'C:\fbxsdk'
  steps:
  - name: Checkout
    uses: actions/checkout@v4

  # MSBuildを使えるようにセットアップ
  - name: Setup MSBuild
    uses: microsoft/setup-msbuild@v2

  # NuGetを使えるようにセットアップ
  - name: Setup NuGet
    uses: nuget/setup-nuget@v2
    with:
     nuget-version: '6.x'
  # NuGetパッケージを復元
  - name: Restore NuGet packages
    run: nuget restore Game.sln

  # FBX SDKインストーラをダウンロード
  - name: Download FBX SDK installer
    shell: powershell
    run: |
      $url = 'https://damassets.autodesk.net/content/dam/autodesk/www/files/fbx202037_fbxsdk_vs2022_win.exe'
      Invoke-WebRequest -Uri $url -OutFile '.\FBXInstaller.exe'

  # FBX SDKをインストール
  - name: install FBX SDK
    shell: cmd
    run: |
      FBXInstaller.exe /S /D=C:\fbxsdk

  # Release ビルド
  - name: Build solution(Release x64)
    run: msbuild "Game.sln" /p:Configuration=Release /p:Platform=x64

  - name: Create GitHub Release and upload artifacts
    uses: softprops/action-gh-release@v1
    with:
     files: |
      ./x64/Release/Project1.exe
      Assets/**/*

    # リポジトリ内のリソースにアクセスできるように認証トークンを渡す
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}