name: Run clang-tidy

on: 
 push:
  branches: ['**']

permissions:
 contents: read
 security-events: write

concurrency:
 group: clang-tidy-${{ github.ref }}
 cancel-in-progress: true

jobs:
 setup:
  uses: ./.github/workflows/SetupEnv.yml
 clang-tidy:
  # 環境設定が完了してからジョブを実行する
  needs: setup
  runs-on: windows-latest
  env:
   VCPKG_ROOT: ${{vars.VCPKG_ROOT}}
  steps:
  # キャッシュ削除
  - name: Remove CMake cache
    run: |
     # ビルドツリーを削除
     if (Test-Path out/build/default) { Remove-Item -Recurse -Force out/build/default }
    shell: pwsh

  # キャッシュ再構成
  - name: Reconfigure CMake cache
    run: |
     cmake --preset default

  # clang-tidyを実行
  - name: Run clang-tidy
    run: |
     cmake --build out/build/default --target clang-tidy

  - name: Upload SARIF to GitHub
    uses: github/codeql-action/upload-sarif@v3
    # エラーがあってもSARIFをアップロードする
    if: always() 
    with:
    # SARIFファイルのパス(相対パス)
     sarif_file: tidy-output.sairf
     category: clang-tidy

