name: Setup Env

on:
 workflow_call:
  outputs:
   fbx-cached:
    description: "FBX SDKがキャッシュから復元されたかどうか"
    value: ${{jobs.set-up-environment.outputs.fbx-cached}}

jobs:
 set-up-environment:
  # windows環境で動かす
  runs-on: windows-latest
  outputs:
   fbx-cached: ${{ steps.cache-fbx.outputs.cache-hit }}
  env:
   FBX: 'C:\fbxsdk'
  steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Setup vcpkg
    uses: lukka/run-vcpkg@v11
    with:
     # vcpkgを配置するディレクトリ
     vcpkgDirectory: '${{ vars.VCPKG_ROOT }}'
     # コミットIDをセット
     vcpkgGitCommitId: '${{ vars.VCPKG_COMMIT_ID }}'
     # vcpkg install を実行する
     runVcpkgInstall: true

  - name: Setup CMake
    uses: lukka/get-cmake@latest
  
  # キャッシュ削除
  - name: Remove CMake cache
    run: |
     # ビルドツリーを削除
     if (Test-Path out/build/default) { Remove-Item -Recurse -Force out/build/default }
    shell: pwsh

  # キャッシュ構成
  - name: Configure CMake cache
    run: |
     cmake --preset default

  - name: Restore FBX SDK cache
    id: cache-fbx
    uses: actions/cache@v4
    with:
      path: C:\fbxsdk
      key: fbx-sdk-202037-{{ hashFiles('**/FBXVersion.txt') }}
      restore-keys: |
        fbx-sdk-202037-
      # キャッシュミスでも、失敗判定にしない
      fail-on-cache-miss: false

  # キャッシュミス時のみダウンロード、インストール
  # FBX SDKインストーラをダウンロード
  - name: Download FBX SDK installer(if not cached)
    if: steps.cache-fbx.outputs.cache.hit != 'true'
    shell: powershell
    run: |
      $url = 'https://damassets.autodesk.net/content/dam/autodesk/www/files/fbx202037_fbxsdk_vs2022_win.exe'
      Invoke-WebRequest -Uri $url -OutFile '.\FBXInstaller.exe' -ErrorAction Stop
      Write-Host "FBX SDK installer downloaded"

  # FBX SDKをインストール
  - name: install FBX SDK(if not cached)
    if: steps.cache-fbx.outputs.cache.hit != 'true'
    shell: cmd
    run: |
      FBXInstaller.exe /S /D=C:\fbxsdk
      echo FBX SDK installed to C:\fbxsdk
      dir C:\fbxsdk

  - name: Verify FBX SDK
    shell: powershell
    run: |
      if (-not (Test-Path 'C:\fbxsdk'))
      {
        throw 'FBX SDK not found at C:\fxsdk'
      }
      Write-Host "FBX SDK verified at C:\fbxsdk"